package io.breen.socrates.model;

import io.breen.socrates.util.ObservableChangedEvent;

/**
 * The event that is generated by a SubmittedFileWrapperNode when it enters a completed state.
 */
public class FileReportCompleteEvent extends ObservableChangedEvent<SubmittedFileWrapperNode> {

    public FileReportCompleteEvent(SubmittedFileWrapperNode source) {
        super(source);
    }
}
