package io.breen.socrates.model;

import io.breen.socrates.util.ObservableChangedEvent;

/**
 * The event that is generated by a TestWrapperNode when its TestResult changes.
 */
public class ResultChangedEvent extends ObservableChangedEvent<TestWrapperNode> {

    public final TestResult oldResult;
    public final TestResult newResult;

    public ResultChangedEvent(TestWrapperNode source, TestResult oldResult, TestResult newResult)
    {
        super(source);
        this.oldResult = oldResult;
        this.newResult = newResult;
    }
}
