package io.breen.socrates.model;

import io.breen.socrates.util.ObservableChangedEvent;

/**
 * The event that is generated by a TestWrapperNode when it references an automated test
 * and the test changes stages.
 *
 * @see io.breen.socrates.model.AutomationStage
 */
public class StageChangedEvent extends ObservableChangedEvent<TestWrapperNode> {

    public final AutomationStage oldStage;
    public final AutomationStage newStage;

    public StageChangedEvent(TestWrapperNode source, AutomationStage oldStage,
                             AutomationStage newStage)
    {
        super(source);
        this.oldStage = oldStage;
        this.newStage = newStage;
    }
}
