package io.breen.socrates.model;

import io.breen.socrates.util.ObservableChangedEvent;

/**
 * The event that is generated by a SubmittedFileWrapperNode when all of its tests are complete.
 */
public class TestsCompleteEvent extends ObservableChangedEvent<SubmittedFileWrapperNode> {

    public TestsCompleteEvent(SubmittedFileWrapperNode source) {
        super(source);
    }
}
