package io.breen.socrates.model.event;

import io.breen.socrates.model.wrapper.SubmittedFileWrapperNode;
import io.breen.socrates.util.ObservableChangedEvent;

/**
 * The event that is generated by a SubmittedFileWrapperNode when it changes its "completed" state
 * --- in other words, if it changes from not complete to complete, or the inverse.
 */
public class CompletedStateChangedEvent extends ObservableChangedEvent<SubmittedFileWrapperNode> {

    public final boolean isNowComplete;

    public CompletedStateChangedEvent(SubmittedFileWrapperNode source, boolean isNowComplete) {
        super(source);
        this.isNowComplete = isNowComplete;
    }
}
