package io.breen.socrates.model.event;

import io.breen.socrates.model.wrapper.SubmissionWrapperNode;
import io.breen.socrates.util.ObservableChangedEvent;

/**
 * The event that is generated by a SubmittedFileWrapperNode when a grade report is saved for it.
 */
public class GradeReportSavedEvent extends ObservableChangedEvent<SubmissionWrapperNode> {

    public GradeReportSavedEvent(SubmissionWrapperNode source) {
        super(source);
    }
}
