package io.breen.socrates.model.event;

import io.breen.socrates.model.wrapper.TestWrapperNode;
import io.breen.socrates.util.ObservableChangedEvent;

/**
 * The event that is generated by a TestWrapperNode when its notes field changes.
 */
public class NotesChangedEvent extends ObservableChangedEvent<TestWrapperNode> {

    public NotesChangedEvent(TestWrapperNode source) {
        super(source);
    }
}
